"use strict";

const $=id=>document.getElementById(id);
const authView=$("authView"),mainView=$("mainView"),authForm=$("authForm"),authSubmit=$("authSubmit"),authError=$("authError"),emailInput=$("email"),passwordInput=$("password"),clipboardList=$("clipboardList"),emptyState=$("emptyState"),settingsPanel=$("settingsPanel"),editorModal=$("editorModal"),editorText=$("editorText"),editorError=$("editorError"),toast=$("toast"),confirmModal=$("confirmModal");
let auth=null,db=null,unsubscribeClips=null,unsubscribeDevices=null,authMode="login",editingId=null,deleteId=null,lastUser=null,deviceHeartbeat=null;
const storedId=localStorage.getItem("cm_device_id");
const currentDeviceId=storedId||((crypto.randomUUID&&crypto.randomUUID())||`${Date.now()}-${Math.random().toString(36).slice(2)}`);
localStorage.setItem("cm_device_id",currentDeviceId);

function deviceType(){const w=screen.width,h=screen.height,ua=navigator.userAgent.toLowerCase(),short=Math.min(w,h);if(/ipad|tablet|android(?!.*mobile)/.test(ua)||(short>=600&&short<1000))return"tablet";if(/mobile|iphone|ipod|android/.test(ua)||short<600)return"phone";return"pc"}
function deviceLabel(){const ua=navigator.userAgent;if(/iphone/i.test(ua))return"iPhone";if(/ipad/i.test(ua))return"iPad";if(/android/i.test(ua))return deviceType()==="tablet"?"Android タブレット":"Android スマートフォン";if(/windows/i.test(ua))return"Windows PC";if(/macintosh/i.test(ua))return"Mac";if(/linux/i.test(ua))return"Linux PC";return"ブラウザ端末"}
function iconFor(type){return type==="pc"?'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="1"/><path d="M8 20h8M12 16v4"/></svg>':type==="tablet"?'<svg viewBox="0 0 24 24"><rect x="5" y="2.5" width="14" height="19" rx="2"/><path d="M10 18.5h4"/></svg>':'<svg viewBox="0 0 24 24"><rect x="7" y="2.5" width="10" height="19" rx="2"/><path d="M10.5 18.5h3"/></svg>'}
function fmt(ts){if(!ts)return"-";const d=ts.toDate?ts.toDate():new Date(ts);return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function ageText(ts){if(!ts)return"";const ms=(ts.toDate?ts.toDate():new Date(ts)).getTime()+5*86400000-Date.now();if(ms<=0)return"削除対象";const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24;return d?`あと${d}日`:`あと${h}時間`}
function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\\":"&#92;"}[c]||c))}

function init(){
  if(!window.CM_FIREBASE_CONFIGURED||!window.CM_FIREBASE_CONFIG){showSetup();return}
  try{firebase.initializeApp(window.CM_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore()}catch(e){showSetup();return}
  auth.onAuthStateChanged(user=>user?enterApp(user):enterAuth());
  setupUI();
}
function setupUI(){
  document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");authMode=b.dataset.mode;authSubmit.textContent=authMode==="login"?"ログイン":"アカウントを作成";passwordInput.autocomplete=authMode==="login"?"current-password":"new-password";authError.textContent=""}));
  authForm.addEventListener("submit",async e=>{e.preventDefault();authError.textContent="";authSubmit.disabled=true;try{const email=emailInput.value.trim(),password=passwordInput.value;if(authMode==="login")await auth.signInWithEmailAndPassword(email,password);else await auth.createUserWithEmailAndPassword(email,password)}catch(err){authError.textContent=authErrorText(err)}finally{authSubmit.disabled=false}});
  $("forgotPassword").addEventListener("click",async()=>{const email=emailInput.value.trim();if(!email){authError.textContent="先にメールアドレスを入力してください。";return}try{await auth.sendPasswordResetEmail(email);showToast("パスワード再設定メールを送信しました")}catch(e){authError.textContent=authErrorText(e)}});
  $("settingsButton").addEventListener("click",openSettings);$("closeSettings").addEventListener("click",closeSettings);$("settingsBackdrop").addEventListener("click",closeSettings);$("logoutButton").addEventListener("click",()=>auth.signOut());
  $("newClipboard").addEventListener("click",()=>openEditor());$("closeEditor").addEventListener("click",closeEditor);$("cancelEditor").addEventListener("click",closeEditor);$("editorBackdrop").addEventListener("click",closeEditor);$("saveEditor").addEventListener("click",saveClipboard);
  $("cancelDelete").addEventListener("click",closeDelete);$("confirmBackdrop").addEventListener("click",closeDelete);$("confirmDelete").addEventListener("click",deleteClipboard);
  document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!editorModal.classList.contains("hidden"))closeEditor();else if(!confirmModal.classList.contains("hidden"))closeDelete();else if(!settingsPanel.classList.contains("hidden"))closeSettings()});
}
function authErrorText(e){const map={"auth/invalid-email":"メールアドレスが正しくありません。","auth/user-not-found":"アカウントが見つかりません。","auth/wrong-password":"パスワードが違います。","auth/invalid-credential":"メールアドレスまたはパスワードが違います。","auth/email-already-in-use":"このメールアドレスはすでに登録されています。","auth/weak-password":"パスワードは6文字以上にしてください。","auth/too-many-requests":"試行回数が多すぎます。少し待ってください。","auth/user-disabled":"このアカウントは利用できません。"};return map[e.code]||"処理に失敗しました。入力内容とFirebase設定を確認してください。"}
function showSetup(){authView.classList.remove("hidden");mainView.classList.add("hidden");authError.textContent="Firebase設定を読み込めません。環境変数とビルド設定を確認してください。";authSubmit.disabled=true}
function enterAuth(){authView.classList.remove("hidden");mainView.classList.add("hidden");if(unsubscribeClips)unsubscribeClips();if(unsubscribeDevices)unsubscribeDevices();if(deviceHeartbeat)clearInterval(deviceHeartbeat);lastUser=null}
async function enterApp(user){authView.classList.add("hidden");mainView.classList.remove("hidden");$("accountEmail").textContent=user.email||"-";lastUser=user;await registerDevice(user);subscribeClipboard(user);subscribeDevices(user);if(deviceHeartbeat)clearInterval(deviceHeartbeat);deviceHeartbeat=setInterval(()=>registerDevice(user,true),5*60*1000)}
async function registerDevice(user,heartbeat=false){const ref=db.collection("users").doc(user.uid).collection("devices").doc(currentDeviceId);const base={type:deviceType(),name:deviceLabel(),userAgent:navigator.userAgent,lastSeen:firebase.firestore.FieldValue.serverTimestamp()};if(!heartbeat)base.createdAt=firebase.firestore.FieldValue.serverTimestamp();try{if(heartbeat){await ref.update(base)}else{const snap=await ref.get();if(snap.exists)await ref.update(base);else await ref.set({...base,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}}catch(e){console.warn("device registration failed",e)}}
function subscribeDevices(user){if(unsubscribeDevices)unsubscribeDevices();unsubscribeDevices=db.collection("users").doc(user.uid).collection("devices").orderBy("lastSeen","desc").onSnapshot(snap=>{$("deviceList").innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="device"><div class="device-icon">${iconFor(x.type)}</div><div class="device-info"><div class="device-name">${esc(x.name||"不明な端末")}</div><div class="device-meta">最終利用 ${fmt(x.lastSeen)}</div></div>${d.id===currentDeviceId?'<span class="device-current">この端末</span>':''}</div>`}).join("")||'<p class="section-note">登録端末はありません。</p>'},()=>{$("deviceList").innerHTML='<p class="section-note">端末情報を読み込めませんでした。</p>'})}
function subscribeClipboard(user){if(unsubscribeClips)unsubscribeClips();unsubscribeClips=db.collection("users").doc(user.uid).collection("clipboard").orderBy("updatedAt","desc").onSnapshot(snap=>{clipboardList.innerHTML="";snap.docs.forEach(d=>renderCard(d.id,d.data()));emptyState.classList.toggle("hidden",!snap.empty)},e=>{clipboardList.innerHTML='<p class="error">クリップボードを読み込めませんでした。FirestoreのSecurity Rulesを確認してください。</p>';emptyState.classList.add("hidden");console.error(e)})}
function renderCard(id,x){const card=document.createElement("article");card.className="clipboard-card";const text=x.text||"",long=text.length>240||text.split("\n").length>6;card.innerHTML=`<div class="card-meta"><span>${esc(x.deviceName||"端末")}</span><span class="card-date">作成 ${fmt(x.createdAt)} ・ 更新 ${fmt(x.updatedAt)} ・ ${esc(ageText(x.createdAt))}</span></div><div class="card-text ${long?"collapsed":""}" data-id="${esc(id)}" title="タップして編集">${esc(text)}</div><div class="card-footer"><div class="card-actions"><button class="mini-button copy" type="button">コピー</button><button class="mini-button share" type="button">共有</button><button class="mini-button delete" type="button">削除</button></div>${long?'<button class="expand-button" type="button">全文を表示</button>':''}</div>`;card.querySelector(".card-text").addEventListener("click",()=>openEditor(id,x));card.querySelector(".copy").addEventListener("click",()=>copyText(text));card.querySelector(".share").addEventListener("click",()=>shareText(text));card.querySelector(".delete").addEventListener("click",()=>openDelete(id));const exp=card.querySelector(".expand-button");if(exp)exp.addEventListener("click",()=>{const t=card.querySelector(".card-text");t.classList.toggle("collapsed");exp.textContent=t.classList.contains("collapsed")?"全文を表示":"折りたたむ"});clipboardList.appendChild(card)}
function openEditor(id=null,data=null){editingId=id;$("editorTitle").textContent=id?"クリップボードを編集":"クリップボードを追加";editorText.value=data?.text||"";editorError.textContent="";editorModal.classList.remove("hidden");setTimeout(()=>editorText.focus(),50)}
function closeEditor(){editorModal.classList.add("hidden");editingId=null}
async function saveClipboard(){const text=editorText.value;if(!text.trim()){editorError.textContent="テキストを入力してください。";return}const user=auth.currentUser;if(!user){editorError.textContent="ログインしてください。";return}const base={text,deviceId:currentDeviceId,deviceName:deviceLabel(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{if(editingId){await db.collection("users").doc(user.uid).collection("clipboard").doc(editingId).update(base)}else{await db.collection("users").doc(user.uid).collection("clipboard").add({...base,createdAt:firebase.firestore.FieldValue.serverTimestamp(),expiresAt:firebase.firestore.Timestamp.fromMillis(Date.now()+5*86400000)})}closeEditor();showToast(editingId?"更新しました":"追加しました")}catch(e){console.error(e);editorError.textContent="保存できませんでした。FirestoreのSecurity Rulesを確認してください。"}}
function openDelete(id){deleteId=id;confirmModal.classList.remove("hidden")}
function closeDelete(){confirmModal.classList.add("hidden");deleteId=null}
async function deleteClipboard(){const user=auth.currentUser;if(!user||!deleteId)return;const id=deleteId;closeDelete();try{await db.collection("users").doc(user.uid).collection("clipboard").doc(id).delete();showToast("削除しました")}catch(e){console.error(e);showToast("削除できませんでした")}}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast("コピーしました")}catch{showToast("コピーできませんでした")}}
async function shareText(text){if(!navigator.share){await copyText(text);return}try{await navigator.share({title:"Collaboration Management",text})}catch(e){if(e.name!=="AbortError")showToast("共有できませんでした")}}
function openSettings(){settingsPanel.classList.remove("hidden");settingsPanel.setAttribute("aria-hidden","false")}
function closeSettings(){settingsPanel.classList.add("hidden");settingsPanel.setAttribute("aria-hidden","true")}
let toastTimer;function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2200)}
window.addEventListener("load",init);
