import { firebaseConfig } from "./firebase-config.js";
"use strict";

const $=id=>document.getElementById(id);
const authView=$("authView"),mainView=$("mainView"),authForm=$("authForm"),authSubmit=$("authSubmit"),authError=$("authError"),emailInput=$("email"),passwordInput=$("password"),clipboardList=$("clipboardList"),emptyState=$("emptyState"),settingsPanel=$("settingsPanel"),editorModal=$("editorModal"),editorText=$("editorText"),editorError=$("editorError"),toast=$("toast"),confirmModal=$("confirmModal"),editorUrl=$("editorUrl");
let auth=null,db=null,unsubscribeClips=null,authMode="login",editingId=null,deleteId=null,currentType="text";
const DAY=86400000;

function fmt(ts){if(!ts)return"-";const d=ts.toDate?ts.toDate():new Date(ts);return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function ageText(ts){if(!ts)return"";const ms=(ts.toDate?ts.toDate():new Date(ts)).getTime()+5*DAY-Date.now();if(ms<=0)return"削除対象";const d=Math.floor(ms/DAY),h=Math.floor(ms/3600000)%24;return d?`あと${d}日`:`あと${h}時間`}
function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\\":"&#92;"}[c]||c))}
function typeLabel(t){return t==="url"?"URL":"テキスト"}
function init(){if(!firebaseConfig.apiKey||!firebaseConfig.projectId||!firebaseConfig.appId){showSetup();return}try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);auth=window.__cmFirebaseAuth||firebase.auth();db=firebase.firestore()}catch(e){console.error(e);showSetup();return}setupUI();auth.onAuthStateChanged(user=>user?enterApp(user):enterAuth())}
function setupUI(){
 document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");authMode=b.dataset.mode;authSubmit.textContent=authMode==="login"?"ログイン":"アカウントを作成";passwordInput.autocomplete=authMode==="login"?"current-password":"new-password";authError.textContent=""}));
 authForm.addEventListener("submit",async e=>{e.preventDefault();authError.textContent="";authSubmit.disabled=true;try{const email=emailInput.value.trim(),password=passwordInput.value;if(!email||!password)throw Object.assign(new Error("missing-input"),{code:"cm/missing-input"});if(authMode==="login")await auth.signInWithEmailAndPassword(email,password);else await auth.createUserWithEmailAndPassword(email,password)}catch(err){console.error("Authentication failed",err);authError.textContent=authErrorText(err)}finally{authSubmit.disabled=false}});
 $("forgotPassword").addEventListener("click",async()=>{const email=emailInput.value.trim();if(!email){authError.textContent="先にメールアドレスを入力してください。";return}try{await auth.sendPasswordResetEmail(email);showToast("パスワード再設定メールを送信しました")}catch(e){console.error(e);authError.textContent=authErrorText(e)}});
 $("settingsButton").addEventListener("click",openSettings);$("closeSettings").addEventListener("click",closeSettings);$("settingsBackdrop").addEventListener("click",closeSettings);$("logoutButton").addEventListener("click",()=>auth.signOut());
 $("newClipboard").addEventListener("click",()=>openEditor());$("closeEditor").addEventListener("click",closeEditor);$("cancelEditor").addEventListener("click",closeEditor);$("editorBackdrop").addEventListener("click",closeEditor);$("saveEditor").addEventListener("click",saveData);
 $("cancelDelete").addEventListener("click",closeDelete);$("confirmBackdrop").addEventListener("click",closeDelete);$("confirmDelete").addEventListener("click",deleteData);
 document.querySelectorAll(".type-tab").forEach(b=>b.addEventListener("click",()=>setEditorType(b.dataset.type)));
 document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!editorModal.classList.contains("hidden"))closeEditor();else if(!confirmModal.classList.contains("hidden"))closeDelete();else if(!settingsPanel.classList.contains("hidden"))closeSettings()});
}
function authErrorText(e){const code=e?.code||"";const map={"auth/invalid-email":"メールアドレスが正しくありません。","auth/user-not-found":"アカウントが見つかりません。","auth/wrong-password":"パスワードが違います。","auth/invalid-credential":"メールアドレスまたはパスワードが違います。","auth/email-already-in-use":"このメールアドレスはすでに登録されています。","auth/weak-password":"パスワードは6文字以上にしてください。","auth/too-many-requests":"試行回数が多すぎます。少し待ってください。","auth/user-disabled":"このアカウントは利用できません。","auth/api-key-not-valid":"Firebase APIキーが無効です。Firebase ConsoleのWeb APIキーを確認してください。","auth/operation-not-allowed":"Firebase Consoleでメール/パスワード認証を有効にしてください。","auth/network-request-failed":"Firebaseへの接続に失敗しました。ネットワーク接続を確認してください。","auth/internal-error":"Firebase内部エラーが発生しました。ページを再読み込みしてください。","cm/missing-input":"メールアドレスとパスワードを入力してください。"};return map[code]||`認証に失敗しました。(${code||"unknown"}) ${e?.message||""}`}
function showSetup(){authView.classList.remove("hidden");mainView.classList.add("hidden");authError.textContent="Firebase設定を読み込めません。環境変数とビルド設定を確認してください。";authSubmit.disabled=true}
function enterAuth(){authView.classList.remove("hidden");mainView.classList.add("hidden");if(unsubscribeClips)unsubscribeClips()}
async function enterApp(user){authView.classList.add("hidden");mainView.classList.remove("hidden");$("accountEmail").textContent=user.email||"-";await purgeExpired(user);subscribeData(user)}
async function purgeExpired(user){try{const cutoff=firebase.firestore.Timestamp.fromMillis(Date.now()-5*DAY);const snap=await db.collection("users").doc(user.uid).collection("clipboard").where("createdAt","<=",cutoff).get();await Promise.all(snap.docs.map(d=>d.ref.delete()))}catch(e){console.warn("expired cleanup failed",e)}}
function subscribeData(user){if(unsubscribeClips)unsubscribeClips();unsubscribeClips=db.collection("users").doc(user.uid).collection("clipboard").orderBy("updatedAt","desc").onSnapshot(snap=>{clipboardList.innerHTML="";snap.docs.forEach(d=>renderCard(d.id,d.data()));emptyState.classList.toggle("hidden",!snap.size)},e=>{clipboardList.innerHTML='<p class="error">データを読み込めませんでした。FirestoreのSecurity Rulesを確認してください。</p>';emptyState.classList.add("hidden");console.error(e)})}
function renderCard(id,x){const card=document.createElement("article");card.className="clipboard-card";const text=x.text||x.url||"",long=text.length>240||text.split("\n").length>6;let body=x.type==="url"?`<a class="url-card" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a>`:`<div class="card-text ${long?"collapsed":""}" title="タップして編集">${esc(text)}</div>`;card.innerHTML=`<div class="card-meta"><span class="type-badge">${typeLabel(x.type)}</span><span class="card-date">作成 ${fmt(x.createdAt)} ・ 更新 ${fmt(x.updatedAt)} ・ ${esc(ageText(x.createdAt))}</span></div>${body}<div class="card-footer"><div class="card-actions"><button class="mini-button copy" type="button">コピー</button><button class="mini-button share" type="button">共有</button><button class="mini-button delete" type="button">削除</button></div>${long?'<button class="expand-button" type="button">全文を表示</button>':''}</div>`;if(x.type==="text")card.querySelector(".card-text")?.addEventListener("click",()=>openEditor(id,x));card.querySelector(".copy").addEventListener("click",()=>copyData(x));card.querySelector(".share").addEventListener("click",()=>shareData(x));card.querySelector(".delete").addEventListener("click",()=>openDelete(id));const exp=card.querySelector(".expand-button");if(exp)exp.addEventListener("click",()=>{const t=card.querySelector(".card-text");t.classList.toggle("collapsed");exp.textContent=t.classList.contains("collapsed")?"全文を表示":"折りたたむ"});clipboardList.appendChild(card)}
function setEditorType(type){currentType=type;document.querySelectorAll(".type-tab").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$("textFields").classList.toggle("hidden",type!=="text");$("urlFields").classList.toggle("hidden",type!=="url");editorError.textContent=""}
function openEditor(id=null,data=null){editingId=id;$("editorTitle").textContent=id?"データを編集":"データを追加";editorText.value=data?.text||"";editorUrl.value=data?.url||"";editorError.textContent="";setEditorType(data?.type||"text");editorModal.classList.remove("hidden");setTimeout(()=>currentType==="text"?editorText.focus():editorUrl.focus(),50)}
function closeEditor(){editorModal.classList.add("hidden");editingId=null}
async function saveData(){const user=auth.currentUser;if(!user){editorError.textContent="ログインしてください。";return}const save=$("saveEditor");save.disabled=true;editorError.textContent="";try{const now=firebase.firestore.Timestamp.now();const payload={type:currentType,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(currentType==="text"){const text=editorText.value.trim();if(!text)throw new Error("テキストを入力してください。");payload.text=text;payload.url=""}else{const url=editorUrl.value.trim();if(!url||!/^https?:\/\//i.test(url))throw new Error("http:// または https:// から始まるURLを入力してください。");payload.url=url;payload.text=url}if(editingId){await db.collection("users").doc(user.uid).collection("clipboard").doc(editingId).update(payload);showToast("更新しました")}else{payload.createdAt=now;payload.expiresAt=firebase.firestore.Timestamp.fromMillis(now.toMillis()+5*DAY);await db.collection("users").doc(user.uid).collection("clipboard").add(payload);showToast("保存しました")}closeEditor()}catch(e){editorError.textContent=e.message||"保存に失敗しました。"}finally{save.disabled=false}}
async function copyData(x){const value=x.type==="url"?x.url:x.text;if(!value)return;try{await navigator.clipboard.writeText(value);showToast("コピーしました")}catch(e){const ta=document.createElement("textarea");ta.value=value;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();showToast("コピーしました")}}
async function shareData(x){const value=x.type==="url"?x.url:x.text;try{if(navigator.share)await navigator.share({text:value,url:x.type==="url"?x.url:undefined});else{await navigator.clipboard.writeText(value);showToast("共有機能がないためコピーしました")}}catch(e){if(e?.name!=="AbortError")showToast("共有できませんでした")}}
function openDelete(id){deleteId=id;confirmModal.classList.remove("hidden")}
function closeDelete(){confirmModal.classList.add("hidden");deleteId=null}
async function deleteData(){const user=auth.currentUser;if(!user||!deleteId)return;const id=deleteId;const btn=$("confirmDelete");btn.disabled=true;try{await db.collection("users").doc(user.uid).collection("clipboard").doc(id).delete();showToast("削除しました");closeDelete()}catch(e){showToast("削除に失敗しました")}finally{btn.disabled=false}}
function openSettings(){settingsPanel.classList.remove("hidden");settingsPanel.setAttribute("aria-hidden","false")}
function closeSettings(){settingsPanel.classList.add("hidden");settingsPanel.setAttribute("aria-hidden","true")}
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2400)}

init();
