import { firebaseConfig } from "./firebase-config.js";
"use strict";

const $=id=>document.getElementById(id);
const authView=$("authView"),mainView=$("mainView"),authForm=$("authForm"),authSubmit=$("authSubmit"),authError=$("authError"),emailInput=$("email"),passwordInput=$("password"),clipboardList=$("clipboardList"),emptyState=$("emptyState"),settingsPanel=$("settingsPanel"),editorModal=$("editorModal"),editorText=$("editorText"),editorError=$("editorError"),toast=$("toast"),confirmModal=$("confirmModal"),editorUrl=$("editorUrl"),fileInput=$("fileInput"),selectedFile=$("selectedFile");
let auth=null,db=null,storage=null,unsubscribeClips=null,unsubscribeDevices=null,authMode="login",editingId=null,deleteId=null,deviceHeartbeat=null,currentType="text",selectedUpload=null;
const storedId=localStorage.getItem("cm_device_id");
const currentDeviceId=storedId||(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);
localStorage.setItem("cm_device_id",currentDeviceId);
const DAY=86400000;

function deviceType(){const w=screen.width,h=screen.height,ua=navigator.userAgent.toLowerCase(),short=Math.min(w,h);if(/ipad|tablet|android(?!.*mobile)/.test(ua)||(short>=600&&short<1000))return"tablet";if(/mobile|iphone|ipod|android/.test(ua)||short<600)return"phone";return"pc"}
function deviceLabel(){const ua=navigator.userAgent;if(/iphone/i.test(ua))return"iPhone";if(/ipad/i.test(ua))return"iPad";if(/android/i.test(ua))return deviceType()==="tablet"?"Android タブレット":"Android スマートフォン";if(/windows/i.test(ua))return"Windows PC";if(/macintosh/i.test(ua))return"Mac";if(/linux/i.test(ua))return"Linux PC";return"ブラウザ端末"}
function iconFor(type){return type==="pc"?'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="1"/><path d="M8 20h8M12 16v4"/></svg>':type==="tablet"?'<svg viewBox="0 0 24 24"><rect x="5" y="2.5" width="14" height="19" rx="2"/><path d="M10 18.5h4"/></svg>':'<svg viewBox="0 0 24 24"><rect x="7" y="2.5" width="10" height="19" rx="2"/><path d="M10.5 18.5h3"/></svg>'}
function fmt(ts){if(!ts)return"-";const d=ts.toDate?ts.toDate():new Date(ts);return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function ageText(ts){if(!ts)return"";const ms=(ts.toDate?ts.toDate():new Date(ts)).getTime()+5*DAY-Date.now();if(ms<=0)return"削除対象";const d=Math.floor(ms/DAY),h=Math.floor(ms/3600000)%24;return d?`あと${d}日`:`あと${h}時間`}
function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\\":"&#92;"}[c]||c))}
function typeLabel(t){return({text:"テキスト",url:"URL",image:"画像",file:"ファイル"}[t]||"データ")}
function init(){if(!firebaseConfig.apiKey||!firebaseConfig.projectId||!firebaseConfig.appId){showSetup();return}try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);auth=window.__cmFirebaseAuth||firebase.auth();db=firebase.firestore();storage=firebase.storage()}catch(e){console.error(e);showSetup();return}setupUI();auth.onAuthStateChanged(user=>user?enterApp(user):enterAuth())}
function setupUI(){
 document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");authMode=b.dataset.mode;authSubmit.textContent=authMode==="login"?"ログイン":"アカウントを作成";passwordInput.autocomplete=authMode==="login"?"current-password":"new-password";authError.textContent=""}));
 authForm.addEventListener("submit",async e=>{e.preventDefault();authError.textContent="";authSubmit.disabled=true;try{const email=emailInput.value.trim(),password=passwordInput.value;if(!email||!password)throw Object.assign(new Error("missing-input"),{code:"cm/missing-input"});if(authMode==="login")await auth.signInWithEmailAndPassword(email,password);else await auth.createUserWithEmailAndPassword(email,password)}catch(err){console.error("Authentication failed",err);authError.textContent=authErrorText(err)}finally{authSubmit.disabled=false}});
 $("forgotPassword").addEventListener("click",async()=>{const email=emailInput.value.trim();if(!email){authError.textContent="先にメールアドレスを入力してください。";return}try{await auth.sendPasswordResetEmail(email);showToast("パスワード再設定メールを送信しました")}catch(e){console.error("Password reset failed",e);authError.textContent=authErrorText(e)}});
 $("settingsButton").addEventListener("click",openSettings);$("closeSettings").addEventListener("click",closeSettings);$("settingsBackdrop").addEventListener("click",closeSettings);$("logoutButton").addEventListener("click",()=>auth.signOut());
 $("newClipboard").addEventListener("click",()=>openEditor());$("closeEditor").addEventListener("click",closeEditor);$("cancelEditor").addEventListener("click",closeEditor);$("editorBackdrop").addEventListener("click",closeEditor);$("saveEditor").addEventListener("click",saveData);
 $("cancelDelete").addEventListener("click",closeDelete);$("confirmBackdrop").addEventListener("click",closeDelete);$("confirmDelete").addEventListener("click",deleteData);
 document.querySelectorAll(".type-tab").forEach(b=>b.addEventListener("click",()=>setEditorType(b.dataset.type)));
 fileInput.addEventListener("change",()=>setSelectedFile(fileInput.files?.[0]||null));
 const drop=$("dropZone");["dragenter","dragover"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add("dragover")}));["dragleave","drop"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove("dragover")}));drop.addEventListener("drop",e=>setSelectedFile(e.dataTransfer.files?.[0]||null));
 document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!editorModal.classList.contains("hidden"))closeEditor();else if(!confirmModal.classList.contains("hidden"))closeDelete();else if(!settingsPanel.classList.contains("hidden"))closeSettings()});
}
function authErrorText(e){const code=e?.code||"";const map={"auth/invalid-email":"メールアドレスが正しくありません。","auth/user-not-found":"アカウントが見つかりません。","auth/wrong-password":"パスワードが違います。","auth/invalid-credential":"メールアドレスまたはパスワードが違います。","auth/email-already-in-use":"このメールアドレスはすでに登録されています。","auth/weak-password":"パスワードは6文字以上にしてください。","auth/too-many-requests":"試行回数が多すぎます。少し待ってください。","auth/user-disabled":"このアカウントは利用できません。","auth/api-key-not-valid":"Firebase APIキーが無効です。Firebase ConsoleのWeb APIキーを確認してください。","auth/operation-not-allowed":"Firebase Consoleでメール/パスワード認証を有効にしてください。","auth/network-request-failed":"Firebaseへの接続に失敗しました。ネットワーク接続を確認してください。","auth/internal-error":"Firebase内部エラーが発生しました。ページを再読み込みしてください。","cm/missing-input":"メールアドレスとパスワードを入力してください。"};return map[code]||`認証に失敗しました。(${code||"unknown"}) ${e?.message||""}`}
function showSetup(){authView.classList.remove("hidden");mainView.classList.add("hidden");authError.textContent="Firebase設定を読み込めません。環境変数とビルド設定を確認してください。";authSubmit.disabled=true}
function enterAuth(){authView.classList.remove("hidden");mainView.classList.add("hidden");if(unsubscribeClips)unsubscribeClips();if(unsubscribeDevices)unsubscribeDevices();if(deviceHeartbeat)clearInterval(deviceHeartbeat)}
async function enterApp(user){authView.classList.add("hidden");mainView.classList.remove("hidden");$("accountEmail").textContent=user.email||"-";await registerDevice(user);await purgeExpired(user);subscribeData(user);subscribeDevices(user);if(deviceHeartbeat)clearInterval(deviceHeartbeat);deviceHeartbeat=setInterval(()=>registerDevice(user,true),5*60*1000)}
async function registerDevice(user,heartbeat=false){const ref=db.collection("users").doc(user.uid).collection("devices").doc(currentDeviceId);const base={type:deviceType(),name:deviceLabel(),userAgent:navigator.userAgent,lastSeen:firebase.firestore.FieldValue.serverTimestamp()};try{if(heartbeat)await ref.update(base);else{const snap=await ref.get();if(snap.exists)await ref.update(base);else await ref.set({...base,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}}catch(e){console.warn("device registration failed",e)}}
async function purgeExpired(user){try{const cutoff=firebase.firestore.Timestamp.fromMillis(Date.now());const snap=await db.collection("users").doc(user.uid).collection("clipboard").where("expiresAt","<=",cutoff).get();await Promise.all(snap.docs.map(async d=>{const x=d.data();if(x.storagePath){try{await storage.ref(x.storagePath).delete()}catch(e){console.warn("storage cleanup failed",e)}}return d.ref.delete()}))}catch(e){console.warn("expired cleanup failed",e)}}
function subscribeDevices(user){if(unsubscribeDevices)unsubscribeDevices();unsubscribeDevices=db.collection("users").doc(user.uid).collection("devices").orderBy("lastSeen","desc").onSnapshot(snap=>{$("deviceList").innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="device"><div class="device-icon">${iconFor(x.type)}</div><div class="device-info"><div class="device-name">${esc(x.name||"不明な端末")}</div><div class="device-meta">最終利用 ${fmt(x.lastSeen)}</div></div>${d.id===currentDeviceId?'<span class="device-current">この端末</span>':''}</div>`}).join("")||'<p class="section-note">登録端末はありません。</p>'},()=>{$("deviceList").innerHTML='<p class="section-note">端末情報を読み込めませんでした。</p>'})}
function subscribeData(user){if(unsubscribeClips)unsubscribeClips();unsubscribeClips=db.collection("users").doc(user.uid).collection("clipboard").orderBy("updatedAt","desc").onSnapshot(snap=>{clipboardList.innerHTML="";snap.docs.forEach(d=>renderCard(d.id,d.data()));emptyState.classList.toggle("hidden",!snap.size)},e=>{clipboardList.innerHTML='<p class="error">データを読み込めませんでした。FirestoreのSecurity Rulesを確認してください。</p>';emptyState.classList.add("hidden");console.error(e)})}
function renderCard(id,x){const card=document.createElement("article");card.className="clipboard-card";const text=x.text||"",long=(x.type==="text"||x.type==="url")&&(text.length>240||text.split("\n").length>6);let body="";if(x.type==="image"&&x.url)body=`<a class="image-preview" href="${esc(x.url)}" target="_blank" rel="noopener"><img src="${esc(x.url)}" alt="${esc(x.fileName||"画像")}" loading="lazy"></a>`;else if(x.type==="file"&&x.url)body=`<a class="file-card" href="${esc(x.url)}" target="_blank" rel="noopener"><span class="file-icon">↗</span><span><strong>${esc(x.fileName||"ファイル")}</strong><small>${esc(formatSize(x.fileSize))}</small></span></a>`;else if(x.type==="url")body=`<a class="url-card" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a>`;else body=`<div class="card-text ${long?"collapsed":""}" title="タップして編集">${esc(text)}</div>`;card.innerHTML=`<div class="card-meta"><span class="type-badge">${typeLabel(x.type)}</span><span>${esc(x.deviceName||"端末")}</span><span class="card-date">作成 ${fmt(x.createdAt)} ・ 更新 ${fmt(x.updatedAt)} ・ ${esc(ageText(x.createdAt))}</span></div>${body}<div class="card-footer"><div class="card-actions"><button class="mini-button copy" type="button">コピー</button><button class="mini-button share" type="button">共有</button><button class="mini-button delete" type="button">削除</button></div>${long?'<button class="expand-button" type="button">全文を表示</button>':''}</div>`;if(x.type==="text")card.querySelector(".card-text")?.addEventListener("click",()=>openEditor(id,x));card.querySelector(".copy").addEventListener("click",()=>copyData(x));card.querySelector(".share").addEventListener("click",()=>shareData(x));card.querySelector(".delete").addEventListener("click",()=>openDelete(id,x));const exp=card.querySelector(".expand-button");if(exp)exp.addEventListener("click",()=>{const t=card.querySelector(".card-text");t.classList.toggle("collapsed");exp.textContent=t.classList.contains("collapsed")?"全文を表示":"折りたたむ"});clipboardList.appendChild(card)}
function formatSize(n){if(!n)return"";if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;if(n<1073741824)return`${(n/1048576).toFixed(1)} MB`;return`${(n/1073741824).toFixed(1)} GB`}
function setEditorType(type){currentType=type;document.querySelectorAll(".type-tab").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$("textFields").classList.toggle("hidden",type!=="text");$("urlFields").classList.toggle("hidden",type!=="url");$("fileFields").classList.toggle("hidden",type!=="image"&&type!=="file");fileInput.accept=type==="image"?"image/*":"*/*";editorError.textContent=""}
function setSelectedFile(file){selectedUpload=file;selectedFile.textContent=file?`${file.name} ・ ${formatSize(file.size)}`:"";if(file&&file.type.startsWith("image/"))setEditorType("image")}
function openEditor(id=null,data=null){editingId=id;selectedUpload=null;selectedFile.textContent="";fileInput.value="";$("editorTitle").textContent=id?"データを編集":"データを追加";editorText.value=data?.text||"";editorUrl.value=data?.url||"";editorError.textContent="";setEditorType(data?.type||"text");if(data?.type==="image"||data?.type==="file")selectedFile.textContent=data.fileName||"既存ファイルを使用中";editorModal.classList.remove("hidden");setTimeout(()=>editorText.focus(),50)}
function closeEditor(){editorModal.classList.add("hidden");editingId=null;selectedUpload=null}
async function saveData(){const user=auth.currentUser;if(!user){editorError.textContent="ログインしてください。";return}const save=$("saveEditor");save.disabled=true;editorError.textContent="";try{let payload={type:currentType,deviceId:currentDeviceId,deviceName:deviceLabel(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(currentType==="text"){if(!editorText.value.trim())throw Error("テキストを入力してください。");payload.text=editorText.value}else if(currentType==="url"){const value=editorUrl.value.trim();if(!value||!/^https?:\/\//i.test(value))throw Error("http:// または https:// のURLを入力してください。");payload.url=value;payload.text=value}else{if(!selectedUpload&&!editingId)throw Error("ファイルを選択してください。");if(selectedUpload){if(currentType==="image"&&!selectedUpload.type.startsWith("image/"))throw Error("画像ファイルを選択してください。");if(selectedUpload.size>100*1024*1024)throw Error("ファイルは100MB以下にしてください。");const safeName=selectedUpload.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`users/${user.uid}/uploads/${Date.now()}_${Math.random().toString(36).slice(2)}_${safeName}`;const ref=storage.ref(path);await ref.put(selectedUpload);payload.url=await ref.getDownloadURL();payload.storagePath=path;payload.fileName=selectedUpload.name;payload.fileSize=selectedUpload.size;payload.mimeType=selectedUpload.type}else{const snap=await db.collection("users").doc(user.uid).collection("clipboard").doc(editingId).get();Object.assign(payload,snap.data())}}
const col=db.collection("users").doc(user.uid).collection("clipboard");if(editingId)await col.doc(editingId).update(payload);else await col.add({...payload,createdAt:firebase.firestore.FieldValue.serverTimestamp(),expiresAt:firebase.firestore.Timestamp.fromMillis(Date.now()+5*DAY)});const wasEditing=!!editingId;closeEditor();showToast(wasEditing?"更新しました":"データを追加しました")}catch(e){console.error(e);editorError.textContent=e.message||"保存できませんでした。Firebaseの設定とSecurity Rulesを確認してください。"}finally{save.disabled=false}}
function openDelete(id,data){deleteId={id,data};confirmModal.classList.remove("hidden")}
function closeDelete(){confirmModal.classList.add("hidden");deleteId=null}
async function deleteData(){const user=auth.currentUser;if(!user||!deleteId)return;const target=deleteId;closeDelete();try{const ref=db.collection("users").doc(user.uid).collection("clipboard").doc(target.id);const snap=await ref.get();const x=snap.data()||target.data||{};await ref.delete();if(x.storagePath)try{await storage.ref(x.storagePath).delete()}catch(e){console.warn("storage delete failed",e)}showToast("削除しました")}catch(e){console.error(e);showToast("削除できませんでした")}}
function dataToText(x){if(x.type==="url")return x.url||"";if(x.type==="file"||x.type==="image")return x.url||"";return x.text||""}
async function copyData(x){await copyText(dataToText(x))}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast("コピーしました")}catch{showToast("コピーできませんでした")}}
async function shareData(x){const text=dataToText(x);if(!navigator.share){await copyText(text);return}try{await navigator.share({title:`Collaboration Management / ${typeLabel(x.type)}`,text,url:x.type==="url"?x.url:undefined})}catch(e){if(e.name!=="AbortError")showToast("共有できませんでした")}}
function openSettings(){settingsPanel.classList.remove("hidden");settingsPanel.setAttribute("aria-hidden","false")}
function closeSettings(){settingsPanel.classList.add("hidden");settingsPanel.setAttribute("aria-hidden","true")}
let toastTimer;function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2200)}
window.addEventListener("load",init);
